sonar.projectKey=oe-alliance_OpenRecoveryManager
sonar.organization=oe-alliance

# This is the name displayed in the SonarCloud UI, the version is ORM_VERSION of include/version.h.
sonar.projectName=Open Recovery Manager (ORM)

sonar.sourceEncoding=UTF-8

# LVGL is a submodule and the fonts are generated.
sonar.exclusions=lib/**,src/fonts/**
